name: Docker Compose Actions Workflow
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Copy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #SOURCE: "./"
          REMOTE_HOST: "ec2-3-71-184-212.eu-central-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/test"
      - name: Build on my ec-2
        run: sudo docker-compose build --no-cache 
      - name: Deploy to my ec-2
        run: sudo docker-compose -f /test/docker-compose.yaml up -d
